version: 2.1
jobs:
  build:
    docker:
      - image: 'ubuntu-2004:202010-01'
      - image: 'mysql:5.7.24'
        environment:
          # make sure to use something more secure in production
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_DATABASE=warp_core
      - image: 'influxdb:1.5.2'

    steps:
      - checkout
      - run: echo "Hello world!"
      - run: ./gradlew clean test
